language: csharp
dotnet: 3.0
mono: none
git:
  depth: false
cache:
  directories:
    - "/home/travis/.dotnet/tools"
    - "/home/travis/.local/share/powershell/Modules"
if: |
  repo != 3shapeAS/dockerbuild-pwsh OR \
  type = pull_request OR \
  branch = master OR \
  tag IS present
services:
  - docker
dist: bionic
addons:
  apt:
    sources:
      - sourceline: deb http://archive.ubuntu.com/ubuntu bionic main universe
      - sourceline:
          deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod
          bionic main
        key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
      - powershell
install:
  - cd $TRAVIS_BUILD_DIR
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - pwsh -f "./Install-Prerequisites.ps1"
  - export GitVersion_Version=$(dotnet gitversion -output json -showvariable majorminorpatch)
  - export GitVersion_PreReleaseTagWithDash=$(dotnet gitversion -output json -showvariable
    PreReleaseTagWithDash)
  - 'echo "GitVersion says version is : ${GitVersion_Version}"'
  - 'echo "GitVersion says prerelease tag is: ${GitVersion_PreReleaseTagWithDash}"'
script:
  - pwsh -f "./Invoke-Tests.ps1"
deploy:
  skip_cleanup: true
  provider: script
  script: pwsh -f "./Invoke-Publish.ps1"
  on:
    tags: true
    branch: master
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      - secure: f8cnTHCg4oDyDfuHaQs3QGhSulP4bfgojEDUyl9HXPm4/h95RWmuLD0p1S1DO6DSBzUtMCUsyDBUUL+IgSIUv9odH/X2z/4YcOioiqozQHgSFhHEsNqUxq/dseDmNdyoz0/TKSbueWw3Mv1rF3YQsDaRW/yb4nFgQJk15MrJnwpo77+jmAoyk0ZyJSPEH8m2qOkw8Qb8fyH7Ck1WdZH4MEVQojK6SByc6mucINHZG/xtcgcNezrftj5k7wfZBYVQw1xAt85Kriu6o3kGUxLQ6KZdbalazfrtHLir98lTCLXlh6vHrC1tgXxMU4TxLaTh5zkNqJuhpXQuQaH89om+chxLPfVs9O5GXlEurKK1Tpp/3f6cD4KSw5vBNtRIGqt4qqc7+vU+MTtW3Dd3W/5r2DG89n8HskBIs/RJyB0mkmQXGdpCs8cn4dakegCsys+hBfT4yDXeuthO5xPp2w8C5Z2QFRm+WLUDlk5e2tWIr4e4U32oJqAJrayPVVe85SSkLv+Fw4Spy5Jar+tESEYC0n7D3IeTa8oUejTFBXKZDIgTvWkmx9NSYsUadjNAimZug1Yb8jfuae3mFNnHymLXvJvCfl7zzLzu50Asg5yPIlea6tTgD3PEw09L+wOY+wxaeyIw0leqqJR9xFPpsXBen3Dy13aBl0JSdmZQ8bi4wBE=
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.json
