trigger:
  # What branches will trigger a build?
  branches:
    include:
      # Any Pull Request merging into the master branch
      - master

stages:
- stage: Build
  jobs:
  - job: Build
    strategy:
      matrix:
        'Windows':
          VM_IMAGE: 'windows-latest'
        'Linux':
          VM_IMAGE: 'ubuntu-latest'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    # Install the prereqs
    - template: build/common-steps.yml

    # Build and test the project
    - pwsh: Invoke-Psake -buildFile .\Build.ps1 -taskList build, test
      displayName: "Run tests and coverage"

    # Publish code coverage to codecov.io
    - script: codecov -f coverage.json -t $(CODECOV_TOKEN)
      displayName: Upload coverage to codecov.io
      condition: always()

- stage: Publish
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Publish
    pool:
      vmImage: ubuntu-latest

    steps:
    # Install the prereqs
    - template: build/common-steps.yml
    - pwsh: dotnet gitversion /output buildserver /nofetch
      name: Version
    - pwsh: Get-ChildItem Env:Version*
    - pwsh: Get-ChildItem Env:*
    - pwsh: ./Invoke-Publish.ps1
      displayName: Publish to PowerShell Gallery
      condition: succeeded()
      env:
        POWERSHELL_GALLERY_API_TOKEN: "$(POWERSHELL_GALLERY_API_TOKEN)"
        SLACK_TOKEN: "$(SLACK_TOKEN)"
        SLACK_URL: "$(SLACK_URL)"
