trigger:
  # What branches will trigger a build?
  branches:
    include:
      # Any Pull Request merging into the master branch
      - master

stages:
- stage: Build
  jobs:
  - job: Build
    strategy:
      matrix:
        'Windows':
          VM_IMAGE: 'windows-latest'
        'Linux':
          VM_IMAGE: 'ubuntu-latest'
        'macOS':
          VM_IMAGE: 'macOS-latest'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    # Install the prereqs
    - task: DotNetCoreCLI@2
      condition: eq( variables['Agent.OS'], 'Windows_NT' )
      inputs:
        command: "custom"
        custom: "tool"
        arguments: "install --global Codecov.Tool"
    - task: DockerInstaller@0
      inputs:
        dockerVersion: "17.09.0-ce"

    # Build and test the project
    - pwsh: .\Install-Prerequisites.ps1
      displayName: "Install prerequisites"

    - pwsh: Invoke-Psake -buildFile .\Build.ps1 -taskList build, test
      displayName: "Run tests and coverage"

    # Publish code coverage to codecov.io for windows
    - script: codecov -f coverage.json -t $(CODECOV_TOKEN)
      displayName: Upload coverage to codecov.io
      condition: eq( variables['Agent.OS'], 'Windows_NT' )

    # Publish code coverage to codecov.io for unix
    - script: bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN)
      displayName: Upload coverage to codecov.io
      condition: ne( variables['Agent.OS'], 'Windows_NT' )
