# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  # What branches will trigger a build?
  branches:
    include:
      # Any Pull Request merging into the master branch
      - master

pool:
  vmImage: "windows-2019"

steps:
  # Build Tasks
  - powershell: |
      .\Install-Prerequisites.ps1
    displayName: "Install prerequisites"
  - powershell: |
      .\Invoke-Tests.ps1
    displayName: "Run tests and coverage"
